[project]
name = "pill-identifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
<<<<<<< HEAD
dependencies = [
    "fastapi>=0.128.0",
    "python-multipart>=0.0.22",
    "ultralytics>=8.4.8",
    "uvicorn>=0.40.0",
]
=======
dependencies = []
>>>>>>> 33d40a544d22b755c84b2a83fff1c1350abbcfa7
